---
- name: setup webserver
  hosts: all
  become: true
  tasks:
    - name: Install httpd and  php
      ansible.builtin.yum:
        name:
          - httpd
          - php
          - php-common
          - php-cli
          - php-gd
          - php-curl
          - php-mysqlnd
          - php-fpm
          - php-mysqli
        state: latest
        update_cache: yes
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

    - name: custom index.html
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: |
                    Custom Web Page
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

    - name: httpd service enabled
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

    - name: open firewall
      ansible.posix.firewalld:
        service: http
        state: enabled
        immediate: true
        permanent: true
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
        
