---
- name: remove webserver
  hosts: web_server 
  become: true
  tasks:
    - name: disable firewall
      ansible.posix.firewalld:
        service: http
        state: disabled
        immediate: true
        permanent: true
      when: ansible_distribution in ['CentOS', 'RedHat']

    - name: Remove httpd and php
      ansible.builtin.yum:
        name:
          - httpd
          - php
          - php-common
          - php-cli
          - php-gd
          - php-curl
          - php-mysqlnd
          - php-fpm
          - php-mysqli
        state: absent
      when: ansible_distribution in ['CentOS', 'RedHat']

- name: remove database server
  hosts: db_server
  become: true
  tasks:

    - name: remove mariadb-server
      ansible.builtin.yum:
        name: mariadb-server
        state: absent
      when: ansible_distribution in ["CentOS", "RedHat"]


- name: remove file server
  hosts: file_server
  become: true
  tasks:

    - name: remove samba
      ansible.builtin.yum:
        name: samba
        state: absent
      when: ansible_distribution in ["CentOS", "RedHat"]
    
        
