---
- name: setup webserver
  hosts: all
  become: true
  tasks:
    - name: change firewall
      ansible.posix.firewalld:
        service: http
        state: disabled
        immediate: true
        permanent: true
      when: ansible_distribution in ['CentOS', 'RedHat']

    - name: Remove httpd and php
      ansible.builtin.yum:
        name:
          - httpd
          - php
          - php-common
          - php-cli
          - php-gd
          - php-curl
          - php-mysqlnd
          - php-fpm
          - php-mysqli
        state: absent
      when: ansible_distribution in ['CentOS', 'RedHat']
        
